package com.healthcare.portal.email;

import lombok.Data;
import lombok.RequiredArgsConstructor;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

@RestController
@RequestMapping("/internal")
@RequiredArgsConstructor
public class NoShowEmailController {

    private final EmailService emailService;

    @PostMapping("/noshow-email")
    public ResponseEntity<Void> sendNoShowEmail(@RequestBody NoShowEmailRequest request) {
        emailService.sendNoShowIntervention(
                request.getPatientEmail(),
                request.getPatientName(),
                request.getDoctorName(),
                request.getAppointmentDate(),
                request.getSlotStartTime(),
                request.getRiskLevel(),
                request.getInterventionMessage()
        );
        return ResponseEntity.ok().build();
    }

    @Data
    public static class NoShowEmailRequest {
        private String patientEmail;
        private String patientName;
        private String doctorName;
        private String appointmentDate;
        private String slotStartTime;
        private String riskLevel;
        private String interventionMessage;   // LLM-generated by Agent 3
    }
}
